#copy thjis to settings.toml and fill in the info
CIRCUITPY_WIFI_SSID = "wifi-ssid"
CIRCUITPY_WIFI_PASSWORD = "wifi-passaword"

OPENWEATHER_API_KEY = "openweather api key" 
ONION_API_KEY = "onion api key" 
MBTA_API_KEY = "mbta api key"
