CIRCUITPY_WIFI_SSID = "katnet"
CIRCUITPY_WIFI_PASSWORD = "Ruggles#1"

OPENWEATHER_API_KEY = "e218772439e267b3f123e89567d1909c" 
ONION_API_KEY = "e9f5733fbcmsh44e4bbf0b190180p11af65jsn134bd09fba9f" 
MBTA_API_KEY = "3864d934cd784a05993611aa3fb428d9"
